[pytest]
testpaths = tests
filterwarnings =
    ignore:Could not import F16 module; is AeroBench installed\?:UserWarning
    ignore:Could not import HW module; is ROS installed\?:UserWarning
    ignore:The `@auto_move_data` decorator is deprecated.*:pytorch_lightning.utilities.warnings.LightningDeprecationWarning
    ignore:Please use `csc_matrix` from the `scipy\.sparse` namespace.*:DeprecationWarning
    ignore:Please use `coo_matrix` from the `scipy\.sparse` namespace.*:DeprecationWarning
    ignore:Please use `csr_matrix` from the `scipy\.sparse` namespace.*:DeprecationWarning
